### ISSUE TITLE
Daily challenge page

### ISSUE THREAD

**Issue by siva2204** [delta/dalal-street-client#15]
- players will be given set of challenges (each market day)
- types of challenges - `increase cash worth`, `increase stock worth`, `buy specific company stocks`, `increase stock worth`
- have to show progress of the each challenge and players can claim reward at eod.
- all the function like adding, closing and opening challenges will be done in dashboard (checkout admin page in web)
- gamestate stream will stream data from server, when dailychallenge is open, closed, etc.

**Comment by Sudhindra3000** [comment]
Closed with #27
