### ISSUE TITLE
Mortgage Page

### ISSUE THREAD

**Issue by kelpikz** [delta/dalal-street-client#21]
- Users can Mortgage the stocks they own for some quick cash
- Contains a list of all the game stocks with the mortgage value per stock
- Refer to relevant components in [dalal-street-web](https://github.com/delta/dalal-street-web)

**Comment by satyamurti** [comment]
@siva2204 @Sudhindra3000 need to break this page into small tasks. Because looks like mortgage page is depending on other few rpc calls.

**Comment by satyamurti** [comment]
Will discuss this in today's meet at 10 pm IST
