### ISSUE TITLE
Add proper logging

### ISSUE THREAD

**Issue by Sudhindra3000** [delta/dalal-street-client#8]
Right now we are only printing errors with print statements. It will become hard to debug as the project grows in size. Everything in console looks blue 😢. It's hard to see where errors are printed

**Comment by Sudhindra3000** [comment]
Probably some logging library which prints different types of outputs with different colors. So that it's easy to see

**Comment by kelpikz** [comment]
https://pub.dev/packages/logger

This seems like a good enough. Your thought ?

**Comment by Sudhindra3000** [comment]
Ya that looks good. We can use it
